TRUNCATE TABLE AW_STG_BUS_DBO.SWI_STG_CUS_STAY;

create hadoop table AW_STG_BUS_DBO.SWI_STG_CUS_STAY_temp 
like AW_STG_BUS_DBO.SWI_STG_CUS_STAY;


LOAD HADOOP USING FILE URL '/temp/starwood/CUS_STAY_SW_2016.dat'
WITH SOURCE PROPERTIES ('field.delimiter'='|','ignore.extra.fields'='true')
INTO TABLE AW_STG_BUS_DBO.SWI_STG_CUS_STAY_temp OVERWRITE;

insert into AW_STG_BUS_DBO.SWI_STG_CUS_STAY
select GST_MASTER_PROF_ID,
MP_ACPT_ID,
PMS_CONF_ID,
RES_CONF_ID,
GST_ARV_DT,
GST_DPRT_DT,
PROP_MASTER_ID,
PAID_RM_NIGHT_QTY,
FREE_RM_NIGHT_QTY,
ROOM_REVENUE_AMT,
FB_REVENUE_AMT,
OTHER_REVENUE_AMT,
TOTAL_REVENUE_AMT,
BOOKING_DT,
RES_MASTER_CHNL_CD,
BOOKED_RM_TYPE_CD,
FINAL_RM_TYPE_CD,
RM_QTY,
PROP_RATE_PLAN_ID,
RATE_TYPE_CD,
NATURE_OF_STAY_CD,
MBRSHP_TIER_CD,
SPG_CURRENCY_CD, 
rank() over (partition by GST_MASTER_PROF_ID,
MP_ACPT_ID,
PMS_CONF_ID,
RES_CONF_ID,
GST_ARV_DT,
GST_DPRT_DT,
PROP_MASTER_ID,
PAID_RM_NIGHT_QTY,
FREE_RM_NIGHT_QTY,
ROOM_REVENUE_AMT,
FB_REVENUE_AMT,
OTHER_REVENUE_AMT,
TOTAL_REVENUE_AMT,
BOOKING_DT,
RES_MASTER_CHNL_CD,
BOOKED_RM_TYPE_CD,
FINAL_RM_TYPE_CD,
RM_QTY,
PROP_RATE_PLAN_ID,
RATE_TYPE_CD,
NATURE_OF_STAY_CD,
MBRSHP_TIER_CD,
SPG_CURRENCY_CD) rnk
from AW_STG_BUS_DBO.SWI_STG_CUS_STAY_temp ) a 
where a.rnk=1 ;



